### ISSUE TITLE
New Colony NFT

### ISSUE THREAD

**Issue by stinkyfi** [stinkyfi/DoomsDay#4]
- Obolomov wants a new ERC721 contract for his project The Colony

- Create a new ERC-721A contract, that supports 1 free whitelist mint, unlimited payable mints, an airdrop feature while supply last, and a paymentsplitter as beneficiary. Test and auto deployment scripts required.

- Given the timeline alternative routes that where passed on include: On-chain royalties, full audit, and more.

**Comment by atarev-crypto** [comment]
ACSHUALLY, he hates money
